name: Copilot Pre-Firewall Setup
steps:
  - uses: actions/setup-node@v4
    with:
      node-version: '20'
      cache: 'npm'

  - name: Install deps
    run: npm ci

  - name: Install Playwright (pre-firewall)
    run: npx playwright install --with-deps chromium

  - name: Offline build (bundles fixtures)
    run: VITE_OFFLINE=1 npm run build
