# Pre-install steps Copilot should run BEFORE its firewall locks down.
version: 1
steps:
  - name: Use Node 20
    run: |
      corepack enable
      echo "Using Node $(node -v || true)"
  - name: Install deps
    run: npm ci
  - name: Install playwright browsers (chromium only)
    run: npx playwright install chromium
  - name: Build
    run: npm run build
  - name: Validate
    run: |
      node -e "console.log('Build exists:', require('fs').existsSync('dist/index.html'))"
