name: Copilot Pre-Setup
steps:
  - name: Use Node
    run: |
      node -v
      npm -v
  - name: Install dependencies
    run: npm ci
  - name: Install Playwright browsers
    run: npx playwright install chromium
  - name: Build app for testing
    run: npm run build
    env:
      USE_MOCKS: '1'
      NODE_ENV: 'test'
  - name: Cache node_modules
    run: echo "Cache handled by Actions; this is only for Copilot pre-warm."
