name: Copilot Setup Steps
description: Environment setup for Copilot coding agent

steps:
  - name: Update system packages
    run: |
      apt-get update
      apt-get install -y curl git ca-certificates

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '20'
      cache: 'npm'

  - name: Install dependencies
    run: npm install

  - name: Build application
    run: npm run build

  - name: Install Playwright browsers
    run: npx playwright install --with-deps chromium
