name: E2E
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Type check and build
        env:
          USE_MOCKS: '1'
          NODE_ENV: 'test'
          VITE_OFFLINE: 'true'
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright (Chromium) + system deps
        run: npx playwright install --with-deps chromium

      - name: Build app
        env:
          USE_MOCKS: '1'
          NODE_ENV: 'test'
          VITE_OFFLINE: 'true'
        run: npm run build

      - name: Start preview server
        env:
          USE_MOCKS: '1'
          NODE_ENV: 'test'
          VITE_OFFLINE: 'true'
        run: |
          npx vite preview --host 0.0.0.0 --port 4173 --strictPort &> /dev/null &
          npx --yes wait-on http://0.0.0.0:4173

      - name: Run E2E tests
        env:
          PLAYWRIGHT_BASE_URL: 'http://0.0.0.0:4173'
          USE_MOCKS: '1'
          NODE_ENV: 'test'
          VITE_OFFLINE: 'true'
          CI: 'true'
        run: npm run test:e2e:ci

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
