name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright (Chromium) + system deps
        run: npx playwright install --with-deps chromium

      - name: Build app
        env:
          VITE_USE_MOCK_DATA: '1'
        run: npm run build

      - name: Start preview server
        run: |
          npx vite preview --port 4173 --strictPort &> /dev/null &
          npx --yes wait-on http://127.0.0.1:4173

      - name: Run E2E tests
        env:
          PLAYWRIGHT_BASE_URL: 'http://127.0.0.1:4173'
          VITE_USE_MOCK_DATA: '1'
          CI: 'true'
        run: npm run test:e2e:ci

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
