name: e2e
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Type check and build
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Only run E2E tests when 'run-e2e' label is present
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Avoid apt/ESM hits that get firewall-blocked. Only fetch Chromium.
      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Build app
        run: npm run build

      - name: Run E2E
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
