name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Pre-install Node dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (before firewall)
        run: npm install

      - name: Install Playwright browsers (before firewall)
        run: npx playwright install --with-deps chromium

      # Now firewall-safe steps
      - name: Run tests
        run: npm run test:e2e
